# Generated by Django 5.0.14 on 2026-05-04 15:53

import code_editor.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.TextField(help_text="Relative file path in repository"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash of file content", max_length=64
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Detected programming language",
                        max_length=50,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(help_text="File last modification time"),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(auto_now_add=True, help_text="Indexed at"),
                ),
            ],
            options={
                "db_table": "code_editor_indexed_file",
            },
        ),
        migrations.CreateModel(
            name="CodeEditorApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                (
                    "daily_quota",
                    models.IntegerField(
                        default=1000,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rpm_limit",
                    models.IntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_editor_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeEditorRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="API endpoint that was called", max_length=255
                    ),
                ),
                (
                    "provider",
                    models.CharField(help_text="AI provider used", max_length=100),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name that was used", max_length=255
                    ),
                ),
                (
                    "request_kind",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Completion"),
                            ("complete", "Text Completion"),
                            ("edit", "Code Edit"),
                            ("embed", "Embeddings"),
                            ("rerank", "Document Reranking"),
                            ("models", "Model Listing"),
                            ("health", "Health Check"),
                            ("infill", "Fill‑in‑the‑Middle"),
                        ],
                        help_text="Type of request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("rate_limited", "Rate Limited"),
                            ("quota_exceeded", "Quota Exceeded"),
                        ],
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request latency in milliseconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "input_chars",
                    models.IntegerField(
                        default=0,
                        help_text="Number of input characters",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "output_chars",
                    models.IntegerField(
                        default=0,
                        help_text="Number of output characters",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if request failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="code_editor.codeeditorapikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="code_editor_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_request_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Chunk order within file"),
                ),
                ("content", models.TextField(help_text="Chunk content")),
                (
                    "start_line",
                    models.IntegerField(
                        blank=True, help_text="Starting line number", null=True
                    ),
                ),
                (
                    "end_line",
                    models.IntegerField(
                        blank=True, help_text="Ending line number", null=True
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("code", "Code"),
                            ("comment", "Comment"),
                            ("docstring", "Docstring"),
                            ("import", "Import"),
                            ("function", "Function"),
                            ("class", "Class"),
                        ],
                        default="code",
                        max_length=20,
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(default=0, help_text="Estimated token count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "symbol_name",
                    models.CharField(
                        blank=True,
                        help_text="Function or class name if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    code_editor.models.VectorField(
                        blank=True,
                        default=list,
                        help_text="Vector embedding of chunk content (1536-dim). Set after deferred generation.",
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="BAAI/bge-small-en-v1.5",
                        help_text="Model used to generate embedding",
                        max_length=100,
                    ),
                ),
                (
                    "indexed_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="code_editor.indexedfile",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_code_chunk",
            },
        ),
        migrations.CreateModel(
            name="PlanNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_key", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("action_type", models.CharField(blank=True, max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "depends_on",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dependency node keys or ids",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured planning metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="code_editor.plannode",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_plan_node",
                "ordering": ["task_id", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidatePatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "candidate_key",
                    models.CharField(
                        help_text="Stable candidate identifier within a task run",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("applied", "Applied"),
                            ("validated", "Validated"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("patch_metadata", models.JSONField(blank=True, default=dict)),
                ("touched_files", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apply_mode_requested",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest"),
                            ("draft_patch", "Draft Patch"),
                            ("apply_to_workspace", "Apply to Workspace"),
                            ("auto_apply_if_validated", "Auto Apply If Validated"),
                            ("manual_approval_required", "Manual Approval Required"),
                        ],
                        default="suggest",
                        help_text="Requested apply mode for this candidate patch",
                        max_length=32,
                    ),
                ),
                (
                    "apply_mode_effective",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest"),
                            ("draft_patch", "Draft Patch"),
                            ("apply_to_workspace", "Apply to Workspace"),
                            ("auto_apply_if_validated", "Auto Apply If Validated"),
                            ("manual_approval_required", "Manual Approval Required"),
                        ],
                        default="suggest",
                        help_text="Effective apply mode for this candidate after policy evaluation",
                        max_length=32,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Approval status for this candidate patch",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_candidate_patches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_candidate_patches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_patches",
                        to="code_editor.plannode",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_candidate_patch",
                "ordering": ["task_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "code_editor_project",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="code_editor_is_acti_8896fd_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="code_editor_created_60bcea_idx"
                    ),
                    models.Index(fields=["name"], name="code_editor_name_851ed8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(help_text="Provider identifier", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Health status",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Last response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Last error message"),
                ),
                (
                    "last_check",
                    models.DateTimeField(auto_now=True, help_text="Last check"),
                ),
            ],
            options={
                "db_table": "code_editor_provider_health",
                "indexes": [
                    models.Index(
                        fields=["provider_name"], name="code_editor_provide_d6cc2d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="code_editor_status_f73037_idx"
                    ),
                    models.Index(
                        fields=["last_check"], name="code_editor_last_ch_ff7651_idx"
                    ),
                ],
                "unique_together": {("provider_name",)},
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Repository name", max_length=255)),
                ("url", models.URLField(help_text="Repository URL")),
                (
                    "branch",
                    models.CharField(
                        default="main", help_text="Git branch", max_length=100
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("local", "Local"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "vcs_provider",
                    models.CharField(
                        choices=[
                            ("git", "Git"),
                            ("hg", "Mercurial"),
                            ("unknown", "Unknown"),
                        ],
                        default="git",
                        help_text="Version control system provider",
                        max_length=20,
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        blank=True,
                        help_text="Current commit SHA after last sync",
                        max_length=64,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this repository was last synced from its remote source",
                        null=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Remote sync status",
                        max_length=20,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True, help_text="Error message if the last sync failed"
                    ),
                ),
                (
                    "credential_key",
                    models.CharField(
                        blank=True,
                        help_text="Environment or secret key name for repository credentials",
                        max_length=255,
                    ),
                ),
                (
                    "storage_path",
                    models.TextField(
                        blank=True, help_text="Local clone path for remote repository"
                    ),
                ),
                (
                    "indexed_chunk_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of code chunks indexed for this repository",
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this repository was last indexed",
                        null=True,
                    ),
                ),
                (
                    "indexing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("indexing", "Indexing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        help_text="Status of the latest indexing operation",
                        max_length=20,
                    ),
                ),
                (
                    "indexing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if indexing failed or partially succeeded",
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of files indexed in the last successful indexing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="code_editor.project",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_repository",
            },
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="Celery job ID", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "files_processed",
                    models.IntegerField(
                        default=0, help_text="Number of files processed"
                    ),
                ),
                (
                    "chunks_created",
                    models.IntegerField(
                        default=0, help_text="Number of chunks created"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="Started at", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Completed at", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Created at"),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="code_editor.repository",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_ingestion_job",
            },
        ),
        migrations.AddField(
            model_name="indexedfile",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indexed_files",
                to="code_editor.repository",
            ),
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature"),
                            ("bugfix", "Bug Fix"),
                            ("refactor", "Refactor"),
                            ("test", "Test Generation"),
                            ("migration", "Migration"),
                            ("convert", "Convert"),
                            ("analysis", "Analysis"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "instruction",
                    models.TextField(help_text="Primary user instruction for the task"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("retrieving_context", "Retrieving Context"),
                            ("selecting_files", "Selecting Files"),
                            ("generating_patch", "Generating Patch"),
                            ("applying_patch", "Applying Patch"),
                            ("validating", "Validating"),
                            ("scoring", "Scoring"),
                            ("saving_artifacts", "Saving Artifacts"),
                            ("awaiting_review", "Awaiting Review"),
                            ("validation_failed", "Validation Failed"),
                            ("completed_with_warnings", "Completed with Warnings"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("rollback_pending", "Rollback Pending"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        help_text="Current stage key when available",
                        max_length=64,
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured request payload"
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured result payload"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Execution configuration and task options",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Latest or final high-level summary"
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, help_text="Final result summary"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the task failed"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured error details"
                    ),
                ),
                (
                    "launched_via",
                    models.CharField(
                        blank=True,
                        help_text="thread, celery, or other launch mode",
                        max_length=32,
                    ),
                ),
                (
                    "runner_job_id",
                    models.CharField(
                        blank=True,
                        help_text="Queue job identifier when applicable",
                        max_length=255,
                    ),
                ),
                ("cancellation_requested", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "cancellation_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Categorical failure reason when the task does not complete successfully",
                        max_length=64,
                    ),
                ),
                (
                    "requested_apply_mode",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest"),
                            ("draft_patch", "Draft Patch"),
                            ("apply_to_workspace", "Apply to Workspace"),
                            ("auto_apply_if_validated", "Auto Apply If Validated"),
                            ("manual_approval_required", "Manual Approval Required"),
                        ],
                        default="suggest",
                        help_text="Requested apply mode for generated patches",
                        max_length=32,
                    ),
                ),
                (
                    "effective_apply_mode",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest"),
                            ("draft_patch", "Draft Patch"),
                            ("apply_to_workspace", "Apply to Workspace"),
                            ("auto_apply_if_validated", "Auto Apply If Validated"),
                            ("manual_approval_required", "Manual Approval Required"),
                        ],
                        default="suggest",
                        help_text="Effective apply mode used after applying policy decisions",
                        max_length=32,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Approval status for manual review of the task result",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="Repository on which this task operates",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_runs",
                        to="code_editor.repository",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_task_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SelectedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.TextField(help_text="Repository-relative file path")),
                ("why_selected", models.TextField(blank=True)),
                ("selection_score", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ranking evidence and source metadata",
                    ),
                ),
                (
                    "symbol_hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Potential symbols relevant to the task",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indexed_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_selections",
                        to="code_editor.indexedfile",
                    ),
                ),
                (
                    "plan_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_files",
                        to="code_editor.plannode",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_files",
                        to="code_editor.repository",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_files",
                        to="code_editor.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_selected_file",
                "ordering": ["task_id", "rank", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="plannode",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_nodes",
                to="code_editor.taskrun",
            ),
        ),
        migrations.CreateModel(
            name="CandidateScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("syntax_score", models.FloatField(default=0.0)),
                ("validation_score", models.FloatField(default=0.0)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("risk_score", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("final_score", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("scoring_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_patch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="code_editor.candidatepatch",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_scores",
                        to="code_editor.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_candidate_score",
                "ordering": ["task_id", "rank", "-final_score"],
            },
        ),
        migrations.AddField(
            model_name="candidatepatch",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_patches",
                to="code_editor.taskrun",
            ),
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Stage or step name", max_length=64),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Execution order starting at zero"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("retrieving_context", "Retrieving Context"),
                            ("selecting_files", "Selecting Files"),
                            ("generating_patch", "Generating Patch"),
                            ("applying_patch", "Applying Patch"),
                            ("validating", "Validating"),
                            ("scoring", "Scoring"),
                            ("saving_artifacts", "Saving Artifacts"),
                            ("awaiting_review", "Awaiting Review"),
                            ("validation_failed", "Validation Failed"),
                            ("completed_with_warnings", "Completed with Warnings"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancel_requested", "Cancel Requested"),
                            ("cancelled", "Cancelled"),
                            ("rollback_pending", "Rollback Pending"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short summary of what happened in this step",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True, help_text="Accumulated human-readable logs"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured step metadata"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="code_editor.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_task_step",
                "ordering": ["task_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stage_name", models.CharField(max_length=100)),
                ("validation_type", models.CharField(default="command", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("command", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_runs",
                        to="code_editor.candidatepatch",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_runs",
                        to="code_editor.taskstep",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="code_editor.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_validation_run",
                "ordering": ["task_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("targeted", "Targeted"),
                            ("regression", "Regression"),
                            ("smoke", "Smoke"),
                            ("custom", "Custom"),
                        ],
                        default="regression",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("test_command", models.TextField(blank=True)),
                ("targeted_paths", models.JSONField(blank=True, default=list)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("passed_tests", models.PositiveIntegerField(default=0)),
                ("failed_tests", models.PositiveIntegerField(default=0)),
                ("skipped_tests", models.PositiveIntegerField(default=0)),
                ("output", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_runs",
                        to="code_editor.candidatepatch",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="code_editor.taskrun",
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_runs",
                        to="code_editor.validationrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_test_run",
                "ordering": ["task_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("pre_apply", "Pre Apply"),
                            ("post_apply", "Post Apply"),
                            ("rollback", "Rollback"),
                        ],
                        default="baseline",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("restored", "Restored"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "root_path",
                    models.TextField(
                        help_text="Filesystem path to the snapshot root or archive"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("restore_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_snapshots",
                        to="code_editor.candidatepatch",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_snapshots",
                        to="code_editor.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_workspace_snapshot",
                "ordering": ["task_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("plan", "Plan Document"),
                            ("context", "Context Data"),
                            ("selection", "Selected Files"),
                            ("patch", "Patch"),
                            ("log", "Log Output"),
                            ("test", "Test Report"),
                            ("result", "Result"),
                            ("report", "Report"),
                            ("diff_bundle", "Diff Bundle"),
                            ("snapshot", "Snapshot"),
                            ("validation", "Validation Report"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file_path",
                    models.TextField(
                        blank=True,
                        help_text="Filesystem path where the artifact is stored",
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        help_text="Inline textual content when stored directly",
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="code_editor.candidatepatch",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="code_editor.taskrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="code_editor.taskstep",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="code_editor.testrun",
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="code_editor.validationrun",
                    ),
                ),
                (
                    "workspace_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="code_editor.workspacesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "code_editor_task_artifact",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codeeditorapikey",
            index=models.Index(fields=["prefix"], name="code_editor_prefix_77e07d_idx"),
        ),
        migrations.AddIndex(
            model_name="codeeditorapikey",
            index=models.Index(
                fields=["is_active"], name="code_editor_is_acti_f449db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorapikey",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_f03732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_bcda53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["request_kind"], name="code_editor_request_6d46c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(fields=["status"], name="code_editor_status_0ac6b0_idx"),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["provider"], name="code_editor_provide_dd5553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["api_key"], name="code_editor_api_key_e53d36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(fields=["user"], name="code_editor_user_id_af9793_idx"),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["api_key", "created_at"], name="code_editor_api_key_c9ccde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codeeditorrequestlog",
            index=models.Index(
                fields=["provider", "status", "created_at"],
                name="code_editor_provide_38362b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["indexed_file"], name="code_editor_indexed_17cead_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["chunk_type"], name="code_editor_chunk_t_ca6b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_7f399e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["symbol_name"], name="code_editor_symbol__d7c732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["indexed_file", "chunk_type", "chunk_index"],
                name="code_editor_indexed_233953_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codechunk",
            index=models.Index(
                fields=["indexed_file", "symbol_name"], name="chunk_file_symbol_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codechunk",
            unique_together={("indexed_file", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["project"], name="code_editor_project_0bd2e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["indexing_status"], name="code_editor_indexin_ee95ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["last_indexed_at"], name="code_editor_last_in_271bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["sync_status"], name="code_editor_sync_st_4692a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["url"], name="code_editor_url_2fc929_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["branch"], name="code_editor_branch_f68215_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["vcs_provider"], name="code_editor_vcs_pro_91e761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["commit_sha"], name="code_editor_commit__7ecd71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["project", "sync_status", "indexing_status"],
                name="code_editor_project_c2e75d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["repository"], name="code_editor_reposit_ebee64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["status"], name="code_editor_status_3b3eea_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_90e563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["repository"], name="code_editor_reposit_0603de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["file_path"], name="code_editor_file_pa_0c2451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["language"], name="code_editor_languag_521e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["indexed_at"], name="code_editor_indexed_0572e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["repository", "language", "indexed_at"],
                name="code_editor_reposit_1a8797_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indexedfile",
            index=models.Index(
                fields=["repository", "file_path"],
                name="code_editor_reposit_507946_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="indexedfile",
            unique_together={("repository", "file_path")},
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["repository"], name="code_editor_reposit_772fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["task_type"], name="code_editor_task_ty_44a021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(fields=["status"], name="code_editor_status_970a77_idx"),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_32d26b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["started_at"], name="code_editor_started_552b46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["approval_status"], name="code_editor_approva_bdabdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["effective_apply_mode"], name="code_editor_effecti_e1685d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["requested_apply_mode"], name="code_editor_request_4694e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["repository", "status", "created_at"],
                name="code_editor_reposit_3f3a3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="selectedfile",
            index=models.Index(fields=["task"], name="code_editor_task_id_537583_idx"),
        ),
        migrations.AddIndex(
            model_name="selectedfile",
            index=models.Index(
                fields=["repository"], name="code_editor_reposit_7e62e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selectedfile",
            index=models.Index(fields=["rank"], name="code_editor_rank_da6aa3_idx"),
        ),
        migrations.AddConstraint(
            model_name="selectedfile",
            constraint=models.UniqueConstraint(
                fields=("task", "path"), name="code_editor_selected_file_unique_path"
            ),
        ),
        migrations.AddIndex(
            model_name="plannode",
            index=models.Index(fields=["task"], name="code_editor_task_id_db02ca_idx"),
        ),
        migrations.AddIndex(
            model_name="plannode",
            index=models.Index(
                fields=["parent"], name="code_editor_parent__9a7e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannode",
            index=models.Index(fields=["status"], name="code_editor_status_99afaa_idx"),
        ),
        migrations.AddConstraint(
            model_name="plannode",
            constraint=models.UniqueConstraint(
                fields=("task", "node_key"), name="code_editor_plan_node_unique_key"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatescore",
            index=models.Index(fields=["task"], name="code_editor_task_id_eb3c79_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatescore",
            index=models.Index(fields=["rank"], name="code_editor_rank_38d1a8_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatescore",
            index=models.Index(
                fields=["final_score"], name="code_editor_final_s_6d927c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatepatch",
            index=models.Index(fields=["task"], name="code_editor_task_id_0caeba_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatepatch",
            index=models.Index(fields=["status"], name="code_editor_status_79bab2_idx"),
        ),
        migrations.AddIndex(
            model_name="candidatepatch",
            index=models.Index(
                fields=["approval_status"], name="code_editor_approva_5a3af9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatepatch",
            index=models.Index(
                fields=["apply_mode_effective"], name="code_editor_apply_m_9b3a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatepatch",
            index=models.Index(
                fields=["task", "status", "selected_at"],
                name="code_editor_task_id_fef1ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatepatch",
            constraint=models.UniqueConstraint(
                fields=("task", "candidate_key"),
                name="code_editor_candidate_patch_unique_key",
            ),
        ),
        migrations.AddIndex(
            model_name="taskstep",
            index=models.Index(fields=["task"], name="code_editor_task_id_41104c_idx"),
        ),
        migrations.AddIndex(
            model_name="taskstep",
            index=models.Index(fields=["status"], name="code_editor_status_982d86_idx"),
        ),
        migrations.AddIndex(
            model_name="taskstep",
            index=models.Index(fields=["name"], name="code_editor_name_bd6c79_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskstep",
            constraint=models.UniqueConstraint(
                fields=("task", "order"), name="code_editor_task_step_unique_order"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(fields=["task"], name="code_editor_task_id_647df9_idx"),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(fields=["status"], name="code_editor_status_470760_idx"),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["stage_name"], name="code_editor_stage_n_94675e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrun",
            index=models.Index(
                fields=["task", "status", "created_at"],
                name="code_editor_task_id_d86c28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(fields=["task"], name="code_editor_task_id_5840ec_idx"),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(fields=["status"], name="code_editor_status_c764dc_idx"),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["run_type"], name="code_editor_run_typ_000e4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testrun",
            index=models.Index(
                fields=["task", "status", "created_at"],
                name="code_editor_task_id_d816d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacesnapshot",
            index=models.Index(fields=["task"], name="code_editor_task_id_2a87b4_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacesnapshot",
            index=models.Index(fields=["status"], name="code_editor_status_c74272_idx"),
        ),
        migrations.AddIndex(
            model_name="workspacesnapshot",
            index=models.Index(
                fields=["snapshot_type"], name="code_editor_snapsho_7e2c5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["task"], name="code_editor_task_id_599f07_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["artifact_type"], name="code_editor_artifac_d40e11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["created_at"], name="code_editor_created_7bdae0_idx"
            ),
        ),
    ]
