# Generated by Django 5.0.14 on 2026-05-05 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="workspace_path",
            field=models.TextField(
                blank=True, help_text="Server-owned workspace path for this task run"
            ),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(
                fields=["workspace_path"], name="code_editor_workspa_ff5db6_idx"
            ),
        ),
    ]
