from .staging import *  # noqa

SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
